# Generated by Django 3.2.5 on 2024-06-13 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemakaiankamar',
            name='tglmasuk',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 8, 53, 9, 314089)),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='tglpulang',
            field=models.DateTimeField(db_column='tglpulang'),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='tglregistrasi',
            field=models.DateTimeField(db_column='tglpendaftaran'),
        ),
    ]
