# Generated by Django 3.2.5 on 2024-06-13 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20240613_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemakaiankamar',
            name='tglmasuk',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 9, 37, 52, 193398)),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='tglpulang',
            field=models.DateTimeField(blank=True, db_column='tglpulang', null=True),
        ),
    ]
