# Generated by Django 3.2.5 on 2024-07-11 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_pemakaiankamar_tglmasuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='norm',
            field=models.ForeignKey(db_column='id_pasien', on_delete=django.db.models.deletion.DO_NOTHING, to='survey.pasien', to_field='nocm'),
        ),
    ]
