# Generated by Django 3.2.5 on 2024-08-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20240815_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.CharField(db_column='id', max_length=6, primary_key=True, serialize=False)),
                ('nama', models.CharField(db_column='nama', max_length=10)),
            ],
            options={
                'verbose_name': 'Layanan',
                'verbose_name_plural': 'Layanan-Layanan',
                'db_table': 'layanan',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='pelayanan',
            name='id_tempattidur',
        ),
        migrations.RemoveField(
            model_name='pelayanan',
            name='tglkeluar',
        ),
        migrations.RemoveField(
            model_name='pelayanan',
            name='tglmasuk',
        ),
        migrations.AddField(
            model_name='pelayanan',
            name='id_pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey.pegawai', verbose_name='Petugas'),
        ),
        migrations.AddField(
            model_name='pelayanan',
            name='id_pemakaiankamar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey.pemakaiankamar', verbose_name='Lokasi'),
        ),
        migrations.AddField(
            model_name='pelayanan',
            name='tgllayanan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Layanan'),
        ),
        migrations.AddField(
            model_name='pelayanan',
            name='id_layanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey.layanan', verbose_name='Layanan'),
        ),
    ]
