# Generated by Django 3.2.5 on 2024-08-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20240815_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveiKepuasanMasyarakatRev',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('etika_perawat_rate', models.SmallIntegerField(default=0)),
                ('penampilan_perawat_rate', models.SmallIntegerField(default=0)),
                ('kecakapan_perawat_rate', models.SmallIntegerField(default=0)),
                ('ketepatan_perawat_rate', models.SmallIntegerField(default=0)),
                ('komunikatif_perawat_rate', models.SmallIntegerField(default=0)),
                ('komentar_perawat', models.TextField(blank=True, null=True)),
                ('komentar_perawat_suara', models.FileField(null=True, upload_to='survey/voices/perawat/')),
                ('perawat_time_critic', models.DateTimeField(blank=True, null=True)),
                ('etika_dokter_rate', models.SmallIntegerField(default=0)),
                ('penampilan_dokter_rate', models.SmallIntegerField(default=0)),
                ('kecakapan_dokter_rate', models.SmallIntegerField(default=0)),
                ('ketepatan_dokter_rate', models.SmallIntegerField(default=0)),
                ('solutif_dokter_rate', models.SmallIntegerField(default=0)),
                ('komentar_dokter', models.TextField(blank=True, null=True)),
                ('komentar_dokter_suara', models.FileField(null=True, upload_to='survey/voices/dokter/')),
                ('etika_farmasi_rate', models.SmallIntegerField(default=0)),
                ('penampilan_farmasi_rate', models.SmallIntegerField(default=0)),
                ('kecepatan_farmasi_rate', models.SmallIntegerField(default=0)),
                ('ketepatan_farmasi_rate', models.SmallIntegerField(default=0)),
                ('informatif_farmasi_rate', models.SmallIntegerField(default=0)),
                ('komentar_farmasi', models.TextField(blank=True, null=True)),
                ('komentar_farmasi_suara', models.FileField(null=True, upload_to='survey/voices/farmasi/')),
                ('kelengkapan_fasilitas_rate', models.SmallIntegerField(default=0)),
                ('kebersihan_fasilitas_rate', models.SmallIntegerField(default=0)),
                ('kenyamanan_fasilitas_rate', models.SmallIntegerField(default=0)),
                ('kamarmandi_fasilitas_rate', models.SmallIntegerField(default=0)),
                ('kualitas_fasilitas_rate', models.SmallIntegerField(default=0)),
                ('komentar_fasilitas', models.TextField(blank=True, null=True)),
                ('komentar_fasilitas_suara', models.FileField(null=True, upload_to='survey/voices/fasilitas/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dokter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey.pegawai')),
                ('id_registrasi', models.ForeignKey(db_column='id_pendaftaran', on_delete=django.db.models.deletion.DO_NOTHING, to='survey.registrasi', verbose_name='Nomor Registrasi')),
            ],
            options={
                'verbose_name': 'Survei Kepuasan Masyarakat',
                'verbose_name_plural': 'Survei-Survei Kepuasan Masyarakat',
                'db_table': 'survei_rev',
                'managed': True,
            },
        ),
    ]
